apps:
  - name: paper
    script: server.js
    log_date_format: MM-DD HH:mm
    restart_delay: 1000
    min_uptime: 5000
    max_restarts: 4
  - name: paper-dev
    script: server.js
    log_date_format: MM-DD HH:mm
    restart_delay: 5000
    min_uptime: 5000
    max_restarts: 1
    watch: true
    ignore_watch:
      - .git
      - node_modules
      - static